model:
    name: 'DummyRULPredictor'
train_test_split:
    name: 'CRUHTrainTestSplitter'
    # name: 'RandomTrainTestSplitter'
    cell_data_path:
        - 'data/processed/CALCE'
        - 'data/processed/RWTH'
        - 'data/processed/UL_PUR'
        - 'data/processed/HNEI'
feature:
    name: 'VarianceModelFeatureExtractor'
    interp_dims: 1000
    critical_cycles:
        - 2
        - 9
        - 99
    use_precalculated_qdlin: True
label:
    name: 'RULLabelAnnotator'
feature_transformation:
    name: 'ZScoreDataTransformation'
label_transformation:
    name: 'SequentialDataTransformation'
    transformations:
        - name: 'LogScaleDataTransformation'
        - name: 'ZScoreDataTransformation'
