model:
    name: 'MLPRULPredictor'
    in_channels: 1
    channels: 32
    input_height: 1
    input_width: 1000
    epochs: 500
    batch_size: 128
    evaluate_freq: 100
train_test_split:
    name: 'MATRSecondaryTestTrainTestSplitter'
    cell_data_path: 'data/processed/MATR'
feature:
    name: 'VoltageCapacityMatrixFeatureExtractor'
    diff_base: 9
    cycles_to_keep: 99
    max_cycle_index: 99
    use_precalculated_qdlin: True
label:
    name: 'RULLabelAnnotator'
label_transformation:
    name: 'SequentialDataTransformation'
    transformations:
        - name: 'LogScaleDataTransformation'
        - name: 'ZScoreDataTransformation'
