model:
    name: 'LinearRegressionRULPredictor'
train_test_split:
    name: 'MIX100TrainTestSplitter'
    cell_data_path:
        - 'data/processed/CALCE'
        - 'data/processed/RWTH'
        - 'data/processed/UL_PUR'
        - 'data/processed/HNEI'
        - 'data/processed/MATR'
        - 'data/processed/HUST'
feature:
    name: 'FullModelFeatureExtractor'
    interp_dims: 1000
    critical_cycles:
        - 2
        - 9
        - 99
    use_precalculated_qdlin: True
label:
    name: 'RULLabelAnnotator'
feature_transformation:
    name: 'ZScoreDataTransformation'
label_transformation:
    name: 'SequentialDataTransformation'
    transformations:
        - name: 'LogScaleDataTransformation'
        - name: 'ZScoreDataTransformation'
